name: Trigger auto deployment for okay

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/okay-AutoDeployTrigger-2c2f1ad4-5765-4675-b63f-ee320571678d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.OKAY_REGISTRY_USERNAME }}
          password: ${{ secrets.OKAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: arwindersingh46/okay:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OKAY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n okay -g Hexor_group --server docker.io --username  ${{ secrets.OKAY_REGISTRY_USERNAME }} --password ${{ secrets.OKAY_REGISTRY_PASSWORD }}
            az containerapp update -n okay -g Hexor_group --image arwindersingh46/okay:${{ github.sha }}
